version: '3.1'

x-common-variables: &common-variables
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD

services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      <<: *common-variables
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER --dbname=$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  nginx:
    depends_on:
      - client
      - api
    restart: always 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8008:80

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    command: sh -c "yarn typeorm migration:run -d src/data-source.ts && yarn swagger-autogen"
    env_file:
      - .env
    ports:
      - $API_PORT:$API_PORT
    environment:
      <<: *common-variables
      PORT: $API_PORT
      POSTGRES_HOST: db
      POSTGRES_PORT: $POSTGRES_PORT
    stdin_open: true
    tty: true
  
  client:
    # Fix for hot reload for React apps inside of containers
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    command: npm start
    env_file:
      - .env
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./client/:/srv/app
      - /srv/app/node_modules

volumes:
  pgdata: